- @types/swagger-client/index.d.ts
- src/commands/positive.ts
- src/errors/index.ts
- src/errors/invalid-operation-id-error.ts
- src/errors/missing-required-parameters-error.ts
- src/types/parameter-examples.ts
- src/utilities/constants.ts
- src/utilities/oas-schema.ts
- src/utilities/oas-validator.ts
- src/utilities/parameter-wrapper.ts
- test/commands/positive.test.ts
- test/utilities/oas-validator.test.ts
- test/utilities/parameter-wrapper.test.ts
This PR adds validation to example parameters. It also filters out any parameters that failed validation from the execution block to prevent unnecessary calls (and prevent us from overwriting the failure).
In addition I've done some refactoring to separate logic out into smaller methods to reduce cognitive overhead.
> Api 3873/validate parameter types

- src/commands/positive.ts
- src/utilities/oas-schema.ts
- src/utilities/oas-validator.ts
- test/commands/positive.test.ts
This was a fairly simple update. Anywhere `map` was used we could make the change, but anywhere `flatMap` was used we couldn't.
> Convert to async/await where possible

- @types/swagger-client/index.d.ts
- tsconfig.json
This pr supports [API-4324](https://vajira.max.gov/browse/API-4324) by fixing the tsconfig to correctly recognize the custom matcher we made for jest.
Running `npm run test` produces no errors.
> fix custom jest matcher to be recognized

- Jenkinsfile
- package.json
[API-4326](https://vajira.max.gov/browse/API-4326)
This adds [semantic-release](https://github.com/semantic-release/semantic-release) as part of our CI/CD pipeline. With this in place, any build on master will check to see if a new version needs to be released. If so, it will build and release it as well as push the git tags and release back to the repo.
semantic-release uses [formatted commit messages](https://github.com/semantic-release/semantic-release#commit-message-format) to determine when a new release is needed. We have a [follow-up ticket](https://vajira.max.gov/browse/API-4912) to determine and enforce how we want to make these formatted message into our workflow, so for now we won't have a release version.
> Setup semantic release

- src/utilities/validators/base-validator.ts
- src/validation-messages/failures/properties-mismatch.ts
- test/utilities/validators/base-validator.test.ts
This PR is for [API-6202](https://vajira.max.gov/browse/API-6202). It updates the failure message for object property mismatch failures so that only properties that did not match will be displayed instead of displaying all schema properties.
> Update failure message for property mismatch validation failure

- src/utilities/validators/base-validator.ts
- src/validation-messages/warnings/index.ts
- src/validation-messages/warnings/missing-properties.ts
- test/commands/positive.test.ts
- test/utilities/validators/base-validator.test.ts
[API-5845](https://vajira.max.gov/browse/API-5845)
This updates the schema validation to include a warning when there are properties on an object schema that were not included in the actual response.
> Add check for missing optional parameters

- package-lock.json
- package.json
- src/commands/positive.ts
- test/commands/positive.test.ts
- test/fixtures/forms_oas.yaml
[API-6203](https://vajira.max.gov/browse/API-6203)
This updates the positive test to handle local yaml files in addition to json. Remote yaml files are already handled appropriately by the swagger-client library.
In addition, it removes the file flag and changes it to determining whether the path is a file or not internally.
> Update to handle yaml files

- src/commands/positive.ts
- src/utilities/example-group/example-group.factory.ts
- test/utilities/example-group.factory.test.ts
This PR is for [API-5840](https://vajira.max.gov/browse/API-5840). It ensures required and non-required parameters with the `example` field set or a `default` value in the `examples` field will all be merged together into the default parameter group.
> Merge example and examples values into the default example group

- src/commands/positive.ts
- src/commands/types.d.ts
- src/utilities/validators/example-group-validator.ts
- src/utilities/validators/index.ts
- src/utilities/validators/parameter-schema-validator.ts
- src/utilities/validators/parameter-validator.ts
- src/validation-messages/failures/index.ts
- src/validation-messages/failures/invalid-parameter-example.ts
- test/fixtures/forms_oas.yaml
- test/utilities/validators/example-group-validator.test.ts
- test/utilities/validators/parameter-schema-validator.test.ts
- test/utilities/validators/parameter-validator.test.ts
This adds a check to the parameter validator to make sure that the parameter doesn't have both an example and examples key set.
> Add example/examples check to parameter validator

- src/utilities/example-group/example-group.factory.ts
- src/utilities/oas-operation/oas-operation.factory.ts
Story: [API-7947](https://vajira.max.gov/browse/API-7947)
Bug fix for LOAST breaking if Operation Objects contain no Parameter Objects.
> API-7947 LOAST does not break when there are no parameters

- .husky/prepare-commit-msg
- CONTRIBUTING.md
[API-4326](https://vajira.max.gov/browse/API-4326)
Switch to using `npx` so that we don't have to globally install commitizen
Add command to install husky so that hooks work
> API-4326 semantic release fix

- src/utilities/validators/base-validator.ts
- test/utilities/validators/base-validator.test.ts
- Added fix for single value string array for examples.
- Included one new validation test case
- Changes included additional cleanup of BaseValidator.checkExpectedType() method
> API-9258 example array handling

- src/commands/positive.ts
- src/utilities/validators/base-validator.ts
- src/utilities/validators/example-group-validator.ts
- src/utilities/validators/parameter-schema-validator.ts
- src/utilities/validators/response-validator.ts
- src/validation-messages/validation-message.ts
- src/validation-messages/warnings/missing-properties.ts
- test/commands/positive.test.ts
- test/setup-tests.ts
- test/utilities/validators/base-validator.test.ts
- test/utilities/validators/example-group-validator.test.ts
- test/utilities/validators/parameter-schema-validator.test.ts
- test/utilities/validators/response-validator.test.ts
This PR is for [API-10201](https://vajira.max.gov/browse/API-10201). It removes duplicate validation messages from LOAST output by storing validation failures and warnings in maps instead of arrays in the validators. The ValidationMessage object was also updated to add a hash and a count. This way we can count the number of occurrences of each message.
I also updated the validator unit tests and the positive command unit tests. I also did a little refactoring of the positive command unit tests to group like-tests together and try to reuse one of the bigger json blobs that was duplicated over a few tests. I think these tests could use some more refactoring - I'll make a ticket for that work.
> Remove duplicate validation messages from LOAST output

- @types/swagger-client/index.d.ts
- src/commands/positive.ts
- test/commands/positive.test.ts
- test/fixtures/securities/oauth2_token_oas.json
Adding logic to allow promptForSecurityValues function to handle the oauth2 security scheme type. 
Handles security scheme of type:oauth2 (see Security Scheme Object in OAS spec https://swagger.io/specification/) in order to handle some of the API's such as Clinical Health for LOAST.
> Api 12433/handle oauth2 security type

- .gitignore
- README.md
- tsconfig.json
Api 13576 document steps to debug loast
- Added sections to the readme covering how to debug with vscode and webstorm
- Added vscode and webstorm project files to gitignore
- Turned on the sourcemap option for the typscript compiler.  This was key to getting the debuggers to work.
-
> Api 13576/document steps to debug loast

- @types/swagger-client/index.d.ts
- @types/swagger-client/schema.d.ts
- src/commands/positive.ts
- src/utilities/oas-schema/oas-schema.ts
- src/utilities/oas-server/oas-server.factory.ts
- src/utilities/oas-server/oas-server.ts
- test/commands/positive.test.ts
- test/fixtures/community_care_oas.json
- test/fixtures/health_oas_simple.json
- test/fixtures/simple_forms_oas.json
- test/utilities/oas-schema/oas-schema.test.ts
- test/utilities/oas-security/oas-security.factory.test.ts
This PR is for [API-13163](https://vajira.max.gov/browse/API-13163). It adds a server flag to the `positive` command. A server value is not required if the OAS only has one server object - that one will be used. If the flag is not specified when there is more than one server defined in the OAS the user will be prompted for one. The server value is also validated against the server objects in the OAS. If it does not match one for the server objects' `url` values it is considered invalid and LOAST will exit with an error. This seemed like the best way to go because the `swagger-client` will choose the first url in the server list if the value passed in does not match. If the server value is provided and valid it will be passed on to the `execute` method and `swagger-client` will use it to …
> Add a server flag to the positive command

- src/utilities/oas-operation/oas-operation.ts
- test/commands/positive.test-objects.ts
- test/commands/positive.test.ts
This PR focuses on reducing clutter and size of postitive.test.ts. Test objects have been refactored into their own file - positive.test-objects.ts - and imported into postitive.test.ts making it easier to read and maintain. All local tests passed at the time this code was pushed.
> Api 13583/reduce size and eliminate duplicate code

- package.json
- Added package.json change to allow LOAST to be consumed by other modules rather than requiring direct oclif calls
Work is connected to API-14912
> feat: Exposed conductors and results

- README.md
- package-lock.json
- package.json
- src/loast.ts
- src/utilities/file-in/file-in.ts
- Replaced calls to parseUrl with calls to parsePath directly, which was used internally by parsePath and is all we need
- Updated parse-path dependency in package.json and bumped to current version
- Removed circular dependency on loast package
- Fixed a typo in the readme
- Added FEAT tag to trigger a new release
> API-20393 Resolved package vulnerabilities

- src/suites/positive/positive-suite.ts
- test/loast.test.ts
- test/suites/positive/positive-suite.test.ts
The `bin/suites` command now runs the oas suite even if no server is provided or the server is invalid. 
Previously, if an error was thrown inside of the positive suite, it would propagate up and prevent the oas test from being run. Now, the error is handled gracefully and printed to the output. The positive suite will also be skipped, allowing the oas suite to still run.
Example output (if no server is provided):
```
test (Example Group: 2xx Response) positive: Skipped - 'Server value must be specified if OAS contains more than one server'
test (oas-ruleset) oas-ruleset: 7/129 operations failed
```
> API-20569 - run oas tests even if no server is provided.

- src/suites/oas-ruleset/validation/ruleset.yaml
This PR is for [API-24174](https://vajira.max.gov/browse/API-24174). It updates the oas-ruleset va-param-example-required rule syntax to only check the required property if the parameter is not null.
> fix(oas-ruleset suite): update va-param-example-required rule

- src/suites/positive/validation/positive-validator.ts
deal with the root cause
Updated swagger dereferencing logic to handle situations where component references have OAS base path string injected into front of #path.  Previous logic would fail and show "Cannot read properties of null (reading 'properties')" since this would cause references to components that did not exist
> API-28247 Fixes to prevent the ugly error message and 

- Jenkinsfile
Updated Jenkinsfile to use the node image from GHCR instead of dockerhub
> [API-28925] Update Jenkinsfile to use node from GHCR

- src/suites/rulesets/lighthouse-api-standards.yaml
- test/suites/rulesets/fixtures/setup.json
- test/suites/rulesets/fixtures/va-property-names-booleans-fail.json
- test/suites/rulesets/fixtures/va-property-names-booleans-pass.json
Adds rules to check OAS for [proper naming of booleans](https://department-of-veterans-affairs.github.io/lighthouse-api-standards/naming-and-formatting/#booleans)
> API-29864 add rules for api standards boolean naming

- src/suites/rulesets/lighthouse-api-standards.yaml
- test/suites/rulesets/fixtures/setup.json
- test/suites/rulesets/fixtures/va-property-enum-values-upper-case-fail.json
- test/suites/rulesets/fixtures/va-property-enum-values-upper-case-pass.json
Adds a rule to check enum values.
Enums should be UPPER_CASE strings with underscores in place of spaces. API Standards - [naming and formatting](https://department-of-veterans-affairs.github.io/lighthouse-api-standards/naming-and-formatting/#naming-formatting)
> API 30596: API standards ruleset enum values upper case

- .eslintignore
- jest.config.js
- jest.e2e.config.js
- package.json
- test/fixtures/oas/e2e/example_group_validator.json
- test/suites/positive/positive-suite.e2e.ts
Adding an end to end test command for the loast positive suite. E2E tests can be run using `npm run test:e2e`. This PR only includes the end to end test for example group validator-- other validator tests will be added in the future.
> [API-28168] Add an end to end test for positive suite

- src/suites/rulesets/lighthouse-api-standards.yaml
- test/suites/rulesets/fixtures/setup.json
- test/suites/rulesets/fixtures/va-property-date-time-format-fail.json
- test/suites/rulesets/fixtures/va-property-date-time-format-pass.json
Adds a rule to check timestamp (date-time) formats.
Timestamps must be in ISO 8601 format YYYY-MM-DDTHH:MM:SSZ e.g. 2022-10-03T09:00:00Z
API Standards - [Timestamps](https://department-of-veterans-affairs.github.io/lighthouse-api-standards/naming-and-formatting/dates/#timestamps)
> API-31346 API Standards Ruleset: Timestamps Correct Format

- src/suites/rulesets/lighthouse-api-standards.yaml
Some OAS's were failing to complete this test in a timely manner.  This change seems to fix it. Just removing the slashes around the dash fixed it, the other changes are just some cleanup.
> API-32623: change regex that was causing some OASs to not complete

- .github/workflows/notify-security-alerts.yml
Moving security alerts from Team-Quokka channel to Team-Quokka-alerts channel
> Updated slack channel for security alerts
