department-of-veterans-affairs/lighthouse-oas-tests

- README.md
This PR is for [API-4097](https://vajira.max.gov/browse/API-4097). It adds documentation about possible validation failures to the readme.
> Add validation failure documentation to readme

- @types/swagger-client/index.d.ts
- package-lock.json
- package.json
- src/utilities/oas-validator.ts
- src/validation-failures/index.ts
- src/validation-failures/invalid-schema.ts
- test/utilities/oas-validator.test.ts
[API-4230](https://vajira.max.gov/browse/API-4230)
Added tests for the integer change, but there are some uncovered sections with the refactoring that will go into a later PR
> Add integer type check

- .eslintignore
- src/utilities/oas-validator.ts
- test/utilities/oas-validator.test.ts
- tsconfig.eslint.json
- tsconfig.json
[API-4230](https://vajira.max.gov/browse/API-4230)
- Add integer type check
- Add integer typescript type
- Break up object validation function
- add integer test
- fix path issue
- remove extra spreads and use Number api
- remove schema spread
- pass if is integer
- API-4230: Add more tests and fix validation failure logic
> API 4230/add coverage

- README.md
[API-5424](https://vajira.max.gov/browse/API-5424)
Add InvalidOperationId validation failure to README
Name null closer to error name for clarity
> API-5424 update validation failures list

- test/fixtures/forms_oas.json
[API-5542](https://vajira.max.gov/browse/API-5542)
Add schema to findFormByFormName parameter to fix parameter issue﻿
> API-5542 typeerror for forms api

- README.md
- src/utilities/oas-schema/oas-schema.ts
- test/fixtures/example_groups_oas.json
- test/fixtures/facilities_oas.json
This PR fixes the bug in [API-5709](https://vajira.max.gov/browse/API-5709). It also includes some small refactoring to reduce complexity
> Update to use value prop of examples object

- src/validation-messages/warnings/empty-array.ts
- test/commands/positive.test.ts
- test/utilities/validators/base-validator.test.ts
Update the message for the empty array validation warning as indicated in [API-6622](https://vajira.max.gov/browse/API-6622).
> Update message for empty array validation warning

- @types/swagger-client/schema.d.ts
- src/utilities/oas-operation/oas-operation.factory.ts
- test/utilities/oas-operation.factory.test.ts
Story: [API-6106](https://vajira.max.gov/browse/API-6106)
Some of the AC for this ticket seemed to be working before I started working on it. Added test to cover that and updated logic to merge the parameter object into the operation's parameter object.
> API-6106 - Merge parameter object into operation parameter object

- README.md
Story: [API-5843](https://vajira.max.gov/browse/API-5843)
Added a section for Parameter groups to the readme
> Add parameter groups to readme

- CONTRIBUTING.md
- Jenkinsfile
- README.md
- package-lock.json
- test/utilities/oas-schema/oas-schema.test.ts
- test/utilities/validators/parameter-schema-validator.test.ts
This updates our CI pipeline to use the public repo and the newly created VA NPM account. It also updates the documentation for some bits that were missing.
> Switch to publishing to the public repo

- README.md
Removed -f switch from the example
> API-13672 Fix LOAST example command in readme

- README.md
This PR is fo [API-13163](https://vajira.max.gov/browse/API-13163). It updates the readme to include the new server flag.
> Update the readme to include the server flag

- src/commands/positive.ts
- src/validation-messages/failures/invalid-response.ts
- test/commands/positive.test.ts
- status code added to the InvalidResponse failure message
- details written to stderr
> feat: status code added to the InvalidResponse failure message

- src/commands/positive.ts
- src/utilities/example-group/example-group.factory.ts
- src/utilities/example-group/example-group.ts
- src/utilities/validators/example-group-validator.ts
- test/utilities/example-group/example-group.test.ts
- test/utilities/validators/example-group-validator.test.ts
* fix: remove operation property from ExampleGroup
> fix: remove operation property from ExampleGroup

- CONTRIBUTING.md
- PR intended to correct outdated release status
> feat: reports generated in JSON format

- .eslintignore
- src/validation/validation-message.ts
- src/validation/validators/response-validator.ts
- test/validation/validators/response-validator.test.ts
* added warning message indicating unparseable response body
* configured eslint to ignore lib-test folder in addition to lib
> Api 18282/positive test should default

- Jenkinsfile
* removed NPM_TOKEN environment variable from jenkinsfile
* removed unused environment block from jenkinsfile
> Api 20225/break the loast nexus dependency

- README.md
- src/commands/suites-batch.ts
- src/commands/suites.ts
- src/config/config.interface.ts
- src/loast.ts
- test/loast.test.ts
- Added optional id parameter to suites and suites batch
> API-19697/  add cli parameter for specific suites

- src/loast.ts
- src/suites/oas-ruleset/oas-ruleset-suite.ts
- src/suites/positive/positive-suite.ts
- src/suites/suite-factory.ts
- src/suites/suite.ts
- test/suites/oas-ruleset/oas-ruleset-suite.test.ts
- test/suites/positive/positive-suite.test.ts
- test/suites/suite-factory.test.ts
- Updated suite config and Suites base class to better handle shared & unshared configuration setup
> API-19767/  refactor suite config

- Jenkinsfile
Reverts department-of-veterans-affairs/lighthouse-oas-tests#92
> Revert "Api 20225/break the loast nexus dependency"

- src/commands/suites-batch.ts
- src/commands/suites.ts
- src/loast.ts
- src/utilities/constants.ts
- src/utilities/structured-output/json-structured-output.factory.ts
- src/utilities/structured-output/structured-output.interface.ts
- src/validation/oas-result.ts
- test/fixtures/validation/oas-results.ts
- test/loast.test.ts
- Updated JSON & command line text output to include suiteId
- New PR includes NPM version changes to address testing issues
> API-19989/  add suite id to oas result and json output  Attempt 2

- README.md
Made small readme update
PR mostly intended to kick off a new release creation
> API-21181/ Update Docserver Loast integration to support a Set of Suites

- README.md
Another PR to resolve release creation issue
> API-21181/ Release creation test - fix

- README.md
- Another attempt at release creation
> API-21181/  Update Docserver Release fix test

- README.md
> fix: API-21181 creating release attempt 3

- src/commands/suites.ts
- src/utilities/structured-output/json-structured-output.factory.ts
- src/validation/operation-result.ts
Story: [API-21708](https://vajira.max.gov/browse/API-21708)
Add a flag to remove warning from output. Use `-w `or `--warning` to remove warnings from LOAST output.
> API-21708/Ignore Warnings

- README.md
This PR is to trigger a release for a fix that was made in https://github.com/department-of-veterans-affairs/lighthouse-oas-tests/pull/119. Forgot to add semantic-release formatting in the first PR.
> fix(oast-ruleset suite): add check for required schema properties

- README.md
- Creating a new release by fixing a small typo
> feat: API-26681 DocServer & LOAST: Upgrade typescript version

- CONTRIBUTING.md
> feat: release test

- CONTRIBUTING.md
> feat(core): should create release

- CONTRIBUTING.md
- Checking branch name for failure
> feat(core): release test

- @types/swagger-client/index.d.ts
- src/oas-parsing/schema/oas-schema.ts
- src/suites/positive/validation/positive-validator.ts
- test/oas-parsing/schema/oas-schema.test.ts
- Updated SwaggerClient call to be more clear it is asynchronous behind the scenes
> API-27741 LOAST: remove unnecessary async and eslint disable

- test/fixtures/oas/e2e/example_group_validator.json
- test/fixtures/oas/e2e/response_validator.json
- test/suites/positive/positive-suite.e2e.ts
Adding e2e test for the `ResponseValidator`
> [API-30825] Adding e2e test for response validator

- README.md
> fix: force release

- src/commands/suites.ts
- src/validation/oas-result.ts
- test/commands/suites.test.ts
- test/fixtures/validation/oas-results.ts
https://jira.devops.va.gov/browse/API-38877
> API-38877 Make -j output pure JSON

- README.md
- package-lock.json
- package.json
https://jira.devops.va.gov/browse/API-39061
> Upgrade axios
